# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbbTui < Formula
  desc "Swiss SBB/CFF/FFS timetable app for the terminal"
  homepage ""
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Necrom4/sbb-tui/releases/download/v1.2.1/sbb-tui_Darwin_x86_64.tar.gz"
      sha256 "c1b63aa1da07f7899cd95b3f162c53124b9c741ddbf02b6d078cef48c949c907"

      define_method(:install) do
        bin.install "sbb-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Necrom4/sbb-tui/releases/download/v1.2.1/sbb-tui_Darwin_arm64.tar.gz"
      sha256 "7633744a876ac33351c35232c7dd6db5442c6f5c744679ba82e399b62650dd52"

      define_method(:install) do
        bin.install "sbb-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Necrom4/sbb-tui/releases/download/v1.2.1/sbb-tui_Linux_x86_64.tar.gz"
      sha256 "bed056d65fa348e8248fba517da3e2701fe9dbb36f5e9fc53112b7f8e2b15447"
      define_method(:install) do
        bin.install "sbb-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Necrom4/sbb-tui/releases/download/v1.2.1/sbb-tui_Linux_arm64.tar.gz"
      sha256 "2c5f32220bff80b4a549eafa58f0eece45b2d06e77307fba14f53515f609dc7b"
      define_method(:install) do
        bin.install "sbb-tui"
      end
    end
  end
end
